### ISSUE TITLE
css/js linked resources are not loaded properly

### ISSUE THREAD

**Issue by s4muel** [danielkraic/blog.dkraic.com#2]
css/js linked resources are not loaded properly because main page is loaded via https and the rest is trying to load via http only:

```
Mixed Content: The page at 'https://blog.dkraic.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.dkraic.com/css/slim.css'. This request has been blocked; the content must be served over HTTPS.
blog.dkraic.com/:11 Mixed Content: The page at 'https://blog.dkraic.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.dkraic.com/css/highlight.min.css'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by matusk** [comment]
@danielkraic when it will be fixed?

**Comment by danielkraic** [comment]
`lynx --dump dev.dkraic.com`

**Comment by danielkraic** [comment]
`$ notify-send "$(curl -s https://dev.dkraic.com | grep h1 | grep -o ">.*<" | tr -d "><")"`

**Comment by danielkraic** [comment]
will be fixed in Q4 ([source](https://twitter.com/DEVOPS_BORAT/status/309699310252068864))

**Comment by s4muel** [comment]
`notify-send -i appointment-soon "$(curl -s https://dev.dkraic.com | grep h1 | grep -o ">.*<" | tr -d "><")"`
